development:
  domain: https://staging2.doctor.rambler.ru

staging:
  domain: https://staging.doctor.rambler.ru

staging2:
  domain: https://staging2.doctor.rambler.ru

test:
  domain: https://host.com

preprod:
  domain: https://preprod.doctor.rambler.ru

production:
  domain: https://doctor.rambler.ru
