common: &default_settings
  # Required license key associated with your New Relic account.
  license_key: <%= ENV['NEWRELIC_LICENSE_KEY'] %>
  monitor_mode: false
  log_level: info

development:
  <<: *default_settings
  developer_mode: true

test:
  <<: *default_settings

staging:
  <<: *default_settings
  developer_mode: true

staging2:
  <<: *default_settings
  developer_mode: true

preprod:
  <<: *default_settings
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  monitor_mode: <%= ENV['NEW_RELIC_MONITOR_MODE'] %>
  proxy_host: proxy.park.rambler.ru
  proxy_port: 8080

production:
  <<: *default_settings
  app_name: <%= ENV['NEW_RELIC_APP_NAME'] %>
  monitor_mode: <%= ENV['NEW_RELIC_MONITOR_MODE'] %>
  proxy_host: proxy.park.rambler.ru
  proxy_port: 8080
