# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08e0b7b4e5fab6f2c78bff432911222ff14451dd09869497a704ebbae4151cc8dc8be58c6dcebe3da5bf5e242adb2bffbdc84c1fc95f9e7067ad42192099c0bd
test:
  secret_key_base: 08e0b7b4e5fab6f2c78bff432911222ff14451dd09869497a704ebbae4151cc8dc8be58c6dcebe3da5bf5e242adb2bffbdc84c1fc95f9e7067ad42192099c0bd
staging:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
staging2:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
preprod:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
