default_settings: &default_settings
  write_endpoint: http://night.webdav.rambler.tech/doctor
  read_endpoint: http://get.night.webdav.rambler.tech/doctor

development:
  <<: *default_settings
  path: doctor_stage2

test:
  <<: *default_settings
  path: doctor_stage2

staging:
  <<: *default_settings
  path: doctor_stage

staging2:
  <<: *default_settings
  path: doctor_stage2

preprod:
  <<: *default_settings
  path: doctor_preprod

production:
  <<: *default_settings
  path: doctor_prod
