development:
  host: localhost
  port: 6379
test:
  host: <%= ENV.fetch('REDIS_HOST', 'localhost') %>
  port: 6379
staging:
  url: redis://cache01.stage.doctor.rambler.tech:6379
  password: <%= ENV['REDIS_PASSWORD'] %>
staging2:
  url: redis://cache02.stage.doctor.rambler.tech:6379
  password: <%= ENV['REDIS_PASSWORD'] %>
preprod:
  url: redis://mymaster
  password: <%= ENV["REDIS_PASSWORD"] %>
  role: master
  sentinels:
    - host: cache01.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: cache02.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: cache03.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
production:
  url: redis://mymaster
  password: <%= ENV["REDIS_PASSWORD"] %>
  role: master
  sentinels:
    - host: cache01.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: cache02.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: cache03.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
