development:
  url: redis://localhost:6379
test:
  url: redis://<%= ENV.fetch('REDIS_HOST', 'localhost') %>:6379
staging:
  url: redis://queue01.stage.doctor.rambler.tech:6379
  password: <%= ENV["REDIS_PASSWORD"] %>
staging2:
  url: redis://queue02.stage.doctor.rambler.tech:6379
  password: <%= ENV["REDIS_PASSWORD"] %>
preprod:
  url: redis://mymaster
  password: <%= ENV["REDIS_PASSWORD"] %>
  role: master
  sentinels:
    - host: queue01.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: queue02.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: queue03.preprod.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
production:
  url: redis://mymaster
  password: <%= ENV["REDIS_PASSWORD"] %>
  role: master
  sentinels:
    - host: queue01.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: queue02.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
    - host: queue03.doctor.rambler.tech
      port: <%= ENV["SENTINEL_PORT"] %>
      password: <%= ENV["REDIS_PASSWORD"] %>
